### ISSUE TITLE
Just a dummy, maybe, question about upgrading Pleroma-Bot

### ISSUE THREAD

**Issue by aalcaine** [robertoszek/pleroma-bot#111]
Hi, it might be a dummy question maybe, but could you provide a brief guide to **upgrade** Pleroma-bot from 1.1.0 to 1.2.0 (and future versions)?

The installation steps are really clear and easy to follow, but can't find information to upgrade/update.

Thank you!

**Comment by robertoszek** [comment]
Hi!

Sure, no problem.
I assume you installed the bot using the PyPi package (with `pip`)?

You can upgrade to the latest available version everytime by simply running this:

`pip install pleroma-bot --upgrade`

It may be a good idea to add this to the documentation so it's easier to find for people unfamiliar with `pip`.

**Comment by aalcaine** [comment]
Thank you!

Yes, I installed it with `pip` 😊

Thanks a lot!
