### ISSUE TITLE
RSSHub RSS: Handle remaining Twitter URLs and metadata/encoding oddities

### ISSUE THREAD

**Issue by nemobis** [robertoszek/pleroma-bot#132]
Importing an RSSHub RSS feed works very well, but there are a few issues.

Quote tweets are posted with a literal div and a link to the original tweet (though rewritten if nitter_base_url is configured)
> <div class="rsshub-quote">
> </div>

Example: https://respublicae.eu/@danutahuebner/110604120830026002

t.co links aren't always converted. Example: https://respublicae.eu/@danutahuebner/110604122030104574

Retweets use the display name instead of mentioning the `@username`, for example:
> RT PlatformaObywatelska

https://respublicae.eu/@danutahuebner/110604122554679766

Retweets don't convert t.co links, for example:
> RT EPWashingtonDC
> 🧵 1/2 Support to Ukraine, sanctions, security and stability, trade and technology and NATO enlargement were among topics discussed in the latest meeting of the Transatlantic Legislators' Dialogue led by [@radeksikorski](https://respublicae.eu/@radeksikorski) and @RepNateMoran. More details: https://europa.eu/!mRRgC9 https://t.co/ADbqcF0nGt

https://respublicae.eu/@danutahuebner/110604122444876527

Escaped `&amp;` are left lingering, like:

> Re -We agreed on the need for new elections. We discussed modalities &amp; way ahead
> -Arbitrary arrests or mistreatment of prisoners is unacceptable. [@EULEXkosovo](https://respublicae.eu/@EULEXkosovo) will play a more robust role in monitoring
> - The 3 policemen held in Serbia need to be released urgently &amp; unconditionally https://t.co/8xXGUFVAtN

If the `&` is correctly escaped in the RSSHub XML, then maybe we need to parse the XML differently (with a different library which handles escaping automatically?).

That "Re " is also something added by RSSHub, suggesting replies aren't handled as such.

**Comment by nemobis** [comment]
Quote tweets also get their nitter URL truncated, for example https://respublicae.eu/@BasEickhout/110606157846634382 points to https://nitter.lacontrevoie.fr/BasEickhout/status/16711142107496 instead of https://nitter.lacontrevoie.fr/BasEickhout/status/1671114210749607939 . I've not checked whether it's always a 5 characters error.

**Comment by edel79** [comment]
Another improvement with RSSHub (and probably Nitter, too): when a single request get more than one tweet per user, the display order has to be inverted.
Currently the tweets are displayed from newest to oldest. Expected is from oldest to newest, especially for the threads.

**Comment by dawnerd** [comment]
looks like rsshub is dead for twitter feeds :\

**Comment by nemobis** [comment]
Il 21/07/23 05:17, Troy Whiteley ha scritto:
> looks like rsshub is dead for twitter feeds :\

Ouch. Have you tried self-hosting it yet?

**Comment by nemobis** [comment]
This is no longer needed as I switched to [FeedToMastodon](https://production-ready.de/2024/11/24/feed-to-mastodon-en.html). Thank you for the long service!
