### ISSUE TITLE
Disable Bio Import?

### ISSUE THREAD

**Issue by 1337god** [robertoszek/pleroma-bot#46]

**Comment by robertoszek** [comment]
Hi!
I created a new release which added a new mapping called ```twitter_bio``` specifically for this purpose.
#47 
(And I also updated the documentation to reflect this addition: https://robertoszek.github.io/pleroma-bot/gettingstarted/configuration/#mappings)


So if you upgrade to v0.8.8, you could use it in this way on your ```config.yml```:
```yaml
twitter_bio: false
```

If you're using pip, you can upgrade by running this:
```console
pip install pleroma-bot --upgrade
```

**Comment by robertoszek** [comment]
Let me know if that would solve your issue, @1337god

**Comment by robertoszek** [comment]
Closing it for now, feel free to re-open it if you find it inadequate.
