### ISSUE TITLE
Append original tweet timestamp to end of pleroma post for archiving purposes.

### ISSUE THREAD

**Issue by lightnin** [robertoszek/pleroma-bot#50]
Enable, in the config file, the ability to append the original datestamp of the tweet to the end of the toot.
The use case for this is for those who want to archive their old posts from the birdsite by copying them over to their pleroma instance. Since the tweets being copied may be old (in my case, they are up to 5 years old), and the new toot gets a timestamp that reflects its creation date and not the date of the original tweet, this would be very useful.

I realize that this may be out of scope (as was my request for filtering by hashtags - which I thank you for!) But figured I'd throw it in there for those of us who use twitter as an archive for experiments / etc.

**Comment by lightnin** [comment]
The above request assumes it's not possible to post a new toot with the date of its equivalent tweet. If it's possible to give the toot the same date as the tweet, it would be ideal for archiving purposes. (and solve other problems too - like how to get 3000 tweets copied over when the per run limit is 100 and you can't specify date ranges).

**Comment by robertoszek** [comment]
I totally see the usefulness of a feature like this, absolutely.
Would a timestamp on the body of the message be too intrusive?
For example:
```
"Hey! This is my first tweet on this Twitter account, feel free to follow me if you want cooking tips!

[2015-10-13T06:59:52.000Z]
"
```

Regarding the possibility of submitting toots/posts with a date in the past, as far as I can see neither Mastodon's or Pleroma's API support it:

https://docs.joinmastodon.org/methods/statuses/
https://docs.pleroma.social/backend/development/API/differences_in_mastoapi_responses/#statuses

By all means, do let me know if there's a method to publish toots/posts in the past (without admin access to the instance).

**Comment by lightnin** [comment]
Yes, I figured it would be difficult or impossible to set an arbitrary date for the toot based on the tweet's date. So I think the solution of appending the timestamp of the original tweet to the end of the body of the message is the best solution. Assuming it's trivial to reformat dates, I think a format like: 2015/10/13 16:30 would be nice. At least for my case, UTC is also ok.
