### ISSUE TITLE
UnicodeEncodeError Logger exception with iso8859_2 encoding (non UTF-8)

### ISSUE THREAD

**Issue by vserbu** [robertoszek/pleroma-bot#64]
I've got an error, what can I do? This is the error log:

2022-02-12 08:55:45,426 pleroma_bot ERROR: Exception occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pleroma_bot/cli.py", line 363, in main
    config = yaml.safe_load(stream)
  File "/usr/local/lib/python3.8/dist-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.8/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/usr/local/lib/python3.8/dist-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.8/dist-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/usr/local/lib/python3.8/dist-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.8/dist-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/local/lib/python3.8/dist-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/usr/local/lib/python3.8/dist-packages/pleroma_bot/config.yml", line 2, column 17

**Comment by robertoszek** [comment]
Hi @vserbu !

Could you share your config.yml file's content (obscuring the sensitive data, like the tokens, etc.), it seems the YAML parsers is complaining about the formatting but I'm not sure what specifically is causing it.

**Comment by robertoszek** [comment]
I'm wondering if you used the config.yml.sample file on this repo and maybe this line does not have the final ending quote `"`:
https://github.com/robertoszek/pleroma-bot/blob/97bded22834d9d297a7a8d3fb01aec4993855632/config.yml.sample#L41

Which would cause issues while trying to parse it.

**Comment by robertoszek** [comment]
@vserbu 
I could get a similar exception by putting a semicolon `:` inside a value, make sure you don't have something like this on your config as well:
```
pleroma_base_url: https://pleroma.intance:
```

If you really need that semicolon in a mapping's value for whatever reason (specifying a port, for example), you could put it inside quotes:
```
pleroma_base_url: "https://pleroma.instance:8080"
```

**Comment by vserbu** [comment]
I must point out that I could not install pleroma bot with pip install pleroma-bot because i always got:

Could not find a version that satisfies the requirement pleroma-bot (from versions: ) No matching distribution found for pleroma-bot

So I installed it with pip3 install pleroma-bot 

And this is my config.yml (I used minimal configuration) (I removed tokens). I tought that I could use minimal yml, is that the problem? I wanted to mirror ScifiNow twitter account to mastodon. I'm using mastodon, not pleroma, just to point out.
---
 Change this to your target Fediverse instance
pleroma_base_url: https://salocha.online
# How many tweets to get in every execution
# Twitter's API hard limit is 3,200
max_tweets: 40
# Twitter bearer token
twitter_token: 
users:
- twitter_username: SciFiNow
  pleroma_username: SciFiNow
  # Mastodon/Pleroma bearer token
  pleroma_token:

**Comment by robertoszek** [comment]
@vserbu 

Could you comment out using `#` the line:
```
 Change this to your target Fediverse instance
```

**Comment by robertoszek** [comment]
And by the way, if you're using Mastodon you need your account ID (it's a limitation with the API).
more info [here](https://robertoszek.github.io/pleroma-bot/gettingstarted/configuration/#mastodon)

**Comment by vserbu** [comment]
I've found account ID but everything is the same. I tried with complete and not minimal config.yml . I would like to copy/paste complete config.yml here but it is not possible, because the styling is messing with the text. 

Here is the link to my config.yml - https://file.io/QlGdNIYvwUuz

I left XXXXX for all the tokens and keys.  Do I have to #comment the keys I don't use  like:

consumer_key: xxxxxxxxxxxxxxxxxxxxxxxxx
  consumer_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  access_token_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  access_token_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by robertoszek** [comment]
For pasting the content here, you can wrap it with [backticks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks):
````
```
Config's content goes here
```
````

The minimal config should be fine, those keys you mentioned are only needed if the Twitter account you're mirroring has their tweets protected. They're optional but if they are present `pleroma-bot` will try to use them.

Start with something simple first:
```
pleroma_base_url: https://salocha.online
max_tweets: 40
twitter_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
users:
- twitter_username: SciFiNow
  pleroma_username: 1771
  pleroma_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

```
In the link you provided you seem to have repeated users with the same Twitter account too, which I'm not sure it is what you're trying to do.

If you get any errors please provide the output and I'll try to help out.

**Comment by robertoszek** [comment]
@vserbu 
Going by the first error you posted, looks like your encoding is iso8859_2.
Does it make any difference if you run `pleroma-bot` like so?:
```
PYTHONIOENCODING=UTF-8 pleroma-bot
```

**Comment by vserbu** [comment]
I tried with again with minimal config.yml  and with UTF-8 encoding, I think something changed:
...
2022-02-12 17:59:07,905 - pleroma_bot - INFO - config path: /usr/local/lib/python3.8/dist-packages/pleroma_bot/config.yml 
ℹ 2022-02-12 17:59:07,906 - pleroma_bot - INFO - tweets temp folder: /usr/local/lib/python3.8/dist-packages/pleroma_bot/tweets 
ℹ 2022-02-12 17:59:07,909 - pleroma_bot - INFO - ====================================== 
ℹ 2022-02-12 17:59:07,910 - pleroma_bot - INFO - Processing user:       1771 
✖ 2022-02-12 17:59:08,490 - pleroma_bot - ERROR - Exception occurred (cli.py:502) 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pleroma_bot/cli.py", line 398, in main
    user = User(user_item, config, base_path)
  File "/usr/local/lib/python3.8/dist-packages/pleroma_bot/cli.py", line 207, in __init__
    self._get_twitter_info()
  File "/usr/local/lib/python3.8/dist-packages/pleroma_bot/_twitter.py", line 68, in _get_twitter_info
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.twitter.com/1.1/users/show.json?screen_name=SciFiNow

**Comment by vserbu** [comment]
Just to clarify, I'm trying to mirror twitter account @ScifiNow (I just picked it for testing reasons).
I'm admin at salocha.online mastodon instance and I created there a bot account named @mastobots@salocha.online and it has ID 1771. From there I'm using bearer token and from twitter bearer token too.

**Comment by robertoszek** [comment]
Does your Twitter API project has Elevated access?
You can request it [here](https://developer.twitter.com/en/portal/products/elevated)

It was introduced recently and it is [needed for Twitter's API v1.1](https://robertoszek.github.io/pleroma-bot/gettingstarted/beforerunning/#before-running)
#55

**Comment by vserbu** [comment]
No, maybe that is a problem. I thought that for this purpose I need only basic api?

**Comment by vserbu** [comment]
Hmm...I'm not sure they will approve me v2 for Mastodon bots. Do you have bots working with this script and using v1.1 api?

**Comment by vserbu** [comment]
Aha, I understand. I'll try.

**Comment by vserbu** [comment]
Of course, and thank you for the really fine script with lots of options included. I hope I'm not going to abuse it, my primary intention was to select few interesting sci-fi twitter accounts and bot them to mastodon.

I suppose I have to make some cron job to run the script every hour or so to pick up the new tweets?

**Comment by robertoszek** [comment]
Yeah, to abuse I think you would have to be doing millions of requests a day, I'm pretty sure you won't run into issues on that front.

And yes, you can use cron or a systemd service to fetch new tweets periodically:
https://robertoszek.github.io/pleroma-bot/gettingstarted/automateit/#automate-it

**Comment by robertoszek** [comment]
Oh, and I forgot to add that `twitter_username` can be a list (which I could do a better job of explaining on the documentation, to be fair).
So you can add multiple Twitter accounts to be posted on the same Fediverse account (and the tweets will be order chronologically across all of them).
Your config would look something like this if you want to aggregate multiple Twitter accounts into one Mastodon one:
```
pleroma_base_url: https://salocha.online
max_tweets: 40
twitter_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
users:
- twitter_username:
    - SciFiNow
    - SFXmagazine
    - whateverTwitterAccount
  pleroma_username: 1771
  pleroma_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

You lose the ability of getting their profile info (because there's no "main" account) though.

**Comment by vserbu** [comment]
Is there another way to add another twitter username in series so I can get profile info and everything? Like two or more minimal config ymls merged. Are there any rules how to make that config?

**Comment by robertoszek** [comment]
I guess you could achieve that with something along the lines of:
```
pleroma_base_url: https://salocha.online
max_tweets: 40
twitter_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
users:
- twitter_username:
    - SciFiNow
    - SFXmagazine
    - whateverTwitterAccount
  pleroma_username: 1771
  pleroma_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
- twitter_username: SciFiNow
  pleroma_username: 1771
  pleroma_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

This would get the tweets from the 3 Twitter accounts (not updating the Fedi profile),
and then it would process the next config user, see that they're no new tweets to post and finally it would update the profile (bio, profile image and profile banner).

You can add as many users in series as you want.

**Comment by vserbu** [comment]
For some reason I get error for the first (multiple twitter acc:) and the second version (combination).

Here is the error log for the multiple twitter acc: (maybe there is another way to separate twitter accounts?)

. . .
✖ 2022-02-12 22:38:02,208 - pleroma_bot - ERROR - Exception occurred (cli.py:502) 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pleroma_bot/cli.py", line 398, in main
    user = User(user_item, config, base_path)
  File "/usr/local/lib/python3.8/dist-packages/pleroma_bot/cli.py", line 188, in __init__
    self.pinned_tweet_id = self._get_pinned_tweet_id()
  File "/usr/local/lib/python3.8/dist-packages/pleroma_bot/_pin.py", line 136, in _get_pinned_tweet_id
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.twitter.com/2/users/by/username/-SciFiNow%20-Startrek?user.fields=pinned_tweet_id&expansions=pinned_tweet_id&tweet.fields=entities

**Comment by robertoszek** [comment]
It looks like it's taking the `twitter_username` value as a string, weird.
Are you sure there is an space between the dashes `-` and the values?
```
- twitter_username:
    - SciFiNow
    - SFXmagazine
    - whateverTwitterAccount
```
instead of:
```
- twitter_username:
    -SciFiNow
    -SFXmagazine
    -whateverTwitterAccount
```
If that's not it, maybe sharing your current config could help us find what the issue is.

**Comment by vserbu** [comment]
You were right, one again, the space between the dashes were missing. Tnx.

**Comment by robertoszek** [comment]
Hey @vserbu !
Hopefully the latest version [v1.0.2](https://github.com/robertoszek/pleroma-bot/releases/tag/1.0.2) fixed the UnicodeEncodeError you encountered in the past.
If not (or if you run into any other bugs), feel free to open a new issue, have a nice day!
