### ISSUE TITLE
Expand URLs in profile bio too

### ISSUE THREAD

**Issue by nemobis** [robertoszek/pleroma-bot#80]
Currently the URLs in profile bios are not expanded, for instance https://respublicae.eu/@peterliese contains
> Impressum: https://t.co/gOXDmFJjsx

which is a link to https://peter-liese.de/index.php/impressum . I think the reason for this is that URLs in bios count against the character limit. So I guess there are two possibilities if you want to change this:
* expand the URL but keep the t.co short URL if it wouldn't otherwise fit in the space;
* support URL shortening via kutt.it (https://pypi.org/project/kutt/ ), add a configuration variable to pick a kutt instance.

**Comment by robertoszek** [comment]
Good suggestion, I pushed the changes needed to `1.0.3rc12`:
```
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pleroma-bot==1.0.3rc12
```
On this version, the URLs are expanded if the bio length does not exceed the Fedi instance's limit.

Regarding the use of third-party url shorteners, apparently "URLs in text always count for 23 characters":
https://docs.joinmastodon.org/client/guidelines/
I haven't tested it specifically with the bio text but I assume it gets treated the same way.

So I don't see the value of providing a way to use custom url shorteners with the bot as of right now.

**Comment by nemobis** [comment]
Thanks!

>  I haven't tested it specifically with the bio text but I assume it gets treated the same way.

I only did a simplistic test on my own bio and it seemed to be capped at 500 characters including the "real" URL length, maybe because the bio text is shown as is in the profile previews.
