### ISSUE TITLE
Handle alt text/image description

### ISSUE THREAD

**Issue by maltechx** [robertoszek/pleroma-bot#84]
Hi all,
it would be nice if the bot would mirror the alt text of an image on Twitter to the image description on Mastodon.

**Comment by robertoszek** [comment]
Hi!
Yeah, it'd make perfect sense for the bot to do this automatically.

I've implemented the changes on `1.0.3rc14`, feel free to install it and give it a try:
```
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pleroma-bot==1.0.3rc14
```
If you don't find any issues with the changes, they'll be rolled into the next stable release.

**Comment by maltechx** [comment]
Thanks for the fast implementation. I will let you know when I encounter issues.

**Comment by maltechx** [comment]
No issues so far. Bot runs fine as daemon
