### ISSUE TITLE
Videos are not mirrored

### ISSUE THREAD

**Issue by maltechx** [robertoszek/pleroma-bot#85]
Hey,
videos are not mirrored. My logs don't mention any issues.
Source: https://twitter.com/Hetzner_Online/status/1521825499072323584
Result: https://social.cologne/@Hetzner_Online/108243649641750950

**Comment by robertoszek** [comment]
Hi!
Nice find! It looks like this was an extended tweet and that was the main reason it didn't get all the entities.

Could you try with version `1.0.3rc15`? It should be able to mirror these kind of extended tweets.
You can install it like so:
```
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pleroma-bot==1.0.3rc15
```
